# -*- coding: utf-8 -*-
# Copyright 2012-2017 Jan-Philip Gehrcke. See LICENSE file for details.


"""
Multiple clients (running in greenlets that concurrently run in a child
process) request a response from a WSGIServer running in the parent. Each
response is generated by a child process, i.e. each client connection makes
the server process spawn a child.

A greenlet in the parent, the `servelet`, runs the WSGIServer. Each client
connection is handled in its own greenlet running the `hello_world` function.
This delegates the response creation to a child process. The child process
transfers the response back to the greenlet in the parent process via a gipc
pipe. This yields the response to the client.

Each client greenlet validates the response and terminates.

Output on my test system: 100 clients were served within 0.43 s.
"""


MSG = u"YO".encode("ascii")
N = 100


import gevent
from gevent.pywsgi import WSGIServer
import gipc
import time
try:
    import urllib.request as urllib2
except ImportError:
    import urllib2


def main():
    http_server = WSGIServer(('localhost', 0), hello_world, log=None)
    servelet = gevent.spawn(serve, http_server)
    # Wait for server being bound to socket.
    while True:
        if http_server.address[1] != 0:
            break
        gevent.sleep(0.05)
    client = gipc.start_process(
        target=child_test_wsgi_scenario_client,
        args=(http_server.address, ))
    client.join()
    servelet.kill()
    servelet.join()


def serve(http_server):
    http_server.serve_forever()


def hello_world(environ, start_response):
    # Generate response in child process.
    start_response('200 OK', [('Content-Type', 'text/html')])
    with gipc.pipe() as (reader, writer):
        rg = gipc.start_process(
            target=child_test_wsgi_scenario_respgen,
            args=(writer, ))
        response = reader.get()
        rg.join()
    return [response]


def child_test_wsgi_scenario_respgen(writer):
    writer.put(MSG)


def child_test_wsgi_scenario_client(server_address):
    def get():
        assert urllib2.urlopen("http://%s:%s/" % server_address).read() == MSG
    t1 = time.time()
    clientlets = [gevent.spawn(get) for _ in range(N)]
    gevent.joinall(clientlets)
    duration = time.time() - t1
    print("%s clients were served within %.2f s." % (N, duration))


if __name__ == "__main__":

    # Call `urlopen` with `None` in the parent before forking. This works
    # around a special type of segfault in the child after fork on MacOS.
    # Doh! See https://bugs.python.org/issue27126 and
    # https://github.com/jgehrcke/gipc/issues/52
    try:
        import urllib.request as request
    except ImportError:
        import urllib2 as request
    try:
        result = request.urlopen(None)
    except AttributeError:
        pass

    main()

